/**
* SchoolDiary
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param value 
 * @param studentId 
 * @param teacherId 
 * @param subjectId 
 */

data class GradeDto (
    @Json(name = "value")
    val value: kotlin.Int? = null,
    @Json(name = "studentId")
    val studentId: kotlin.Int? = null,
    @Json(name = "teacherId")
    val teacherId: kotlin.Int? = null,
    @Json(name = "subjectId")
    val subjectId: kotlin.Int? = null
) 



